Footersection
MykolaySheremet/project-16-group pull request #14
Opened 2022-05-14 08:42 UTC by MykolaySheremet

1. Сделал Футер 
2.  Иконку Инстаграм добавил как имж

2022-05-14 10:02 UTC, a3avdeev requested changes
с свг иконкой, я так понял не получилось

2022-05-14 10:02 UTC, a3avdeev commented on src/partials/footer.html
> +        <a class=" link footer__social-link" href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer" >
я добавил rel="noopener noreferrer"

2022-05-14 10:02 UTC, a3avdeev commented on src/sass/_footer.scss
> +        border-left: 1px solid var(--secondary-light-text-color);
тут лучше через after делать, я думаю

2022-05-14 13:40 UTC, MykolaySheremet commented on src/partials/footer.html
> +        <a class=" link footer__social-link" href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer" >
сейчас буду делать через свг как заказчик хотел)) с граиадиентом-)

2022-05-14 13:41 UTC, MykolaySheremet commented on src/sass/_footer.scss
> +        border-left: 1px solid var(--secondary-light-text-color);
да -)сейчас буду делать

2022-05-14 15:10 UTC, MykolaySheremet commented on src/sass/_footer.scss
> +        border-left: 1px solid var(--secondary-light-text-color);
авте уже сделал

2022-05-14 23:33 UTC, a3avdeev submitted a review, later dismissed
вроде гуд

2022-05-15 05:35 UTC, a3avdeev approved these changes
Лишние изображения убрать только

2022-05-15 08:00 UTC, merged