header section
MykolaySheremet/project-16-group pull request #16
Opened 2022-05-14 11:29 UTC by a3avdeev

подогнал.
проверяйте, пожалуйста

2022-05-14 16:07 UTC, MykolaySheremet requested changes

2022-05-14 16:07 UTC, MykolaySheremet commented on src/sass/_header.scss
> +    transition-property: fill;
лучше все внести через запятую  trannsition:     и через зяпятую( хороший тон)

2022-05-14 16:07 UTC, MykolaySheremet commented on src/sass/_header.scss
> +    font-family: 'Montserrat';
поубирать везде , font-family , font-style(normal), i font-weigth- (если значение 500)- это все по умолчание у нас идет от боду

2022-05-14 16:07 UTC, MykolaySheremet commented on src/sass/_header.scss
> +    height: 48.53px;
тут висоту задаешь от куда ти ее берешь 48,53?

2022-05-14 18:08 UTC, a3avdeev commented on src/sass/_header.scss
> +    transition-property: fill;
join

2022-05-14 18:08 UTC, a3avdeev commented on src/sass/_header.scss
> +    font-family: 'Montserrat';
delete

2022-05-14 18:08 UTC, a3avdeev commented on src/sass/_header.scss
> +    height: 48.53px;
change

2022-05-15 00:55 UTC, MykolaySheremet approved these changes

2022-05-15 00:55 UTC, merged