section markup
MykolaySheremet/project-16-group pull request #2
Opened 2022-05-12 10:48 UTC by fullstack2002

section ho we do,
section guarantee

2022-05-12 12:28 UTC, MykolaySheremet requested changes

2022-05-12 12:28 UTC, MykolaySheremet commented on src/partials/guarantee.html
> +<section>
Доделать до готовой версии  со стилями уже

2022-05-12 12:28 UTC, MykolaySheremet commented on src/partials/howwedo.html
> +<section>
доделать до готовой версии , иконки СВГ - пока просто оставь путь пустим - его сегодня Оля сделает спрайт вечером или ночью залью.  - тогда допишешь ( или используй  пока пустишку для контроля за блоком).

2022-05-14 15:39 UTC, fullstack2002 commented on src/partials/howwedo.html
> +<section>
Секция готова

2022-05-14 18:44 UTC, MykolaySheremet requested changes

2022-05-14 18:44 UTC, MykolaySheremet commented on src/partials/howwedo.html
> +          <h3 class="how__card_title underline">Classroom and online </span><span class="move_card">learning</span></h3>
</span><span class="move_card">learning</span></h3>   - ОШИБКА - исправь- перед отправкой прошу все коди проверять на валидатор-))

2022-05-14 18:44 UTC, MykolaySheremet commented on src/sass/_howwedo.scss
> +  width: 280px;
убрать высоту карточек- карточки вистота регулируеться их содержимим

2022-05-15 10:34 UTC, a3avdeev commented on src/partials/guarantee.html
> +    <h2>We guarantee</h2>
не назначены классы

2022-05-15 10:34 UTC, a3avdeev commented on src/partials/guarantee.html
> +    <ul>
тут тоже не назначены классы

2022-05-15 17:10 UTC, merged