add variables
MykolaySheremet/project-16-group pull request #4
Opened 2022-05-12 21:08 UTC by Alena-007

add variables

2022-05-12 21:57 UTC, MykolaySheremet requested changes

2022-05-12 21:57 UTC, MykolaySheremet commented on src/sass/_variables.scss
> +:root {
мы вроде   хотели же все добавить  в паршал  __common (  лучше туда перенеси  ) - а то потом снова придется обновлять ветку -  так как придется вносить изменения подключения нового паршала в main.scss (  ну и комменты оставляй - только поправь  те 2 которые в слаке писал - если согласна) - и зальем его обновим.

2022-05-12 22:21 UTC, Alena-007 commented on src/sass/_variables.scss
> +:root {
Перенесла в __common
С комментами согласна - поправила

2022-05-13 06:46 UTC, MykolaySheremet approved these changes

2022-05-13 06:47 UTC, merged